global:
  skip_genome_workflow: false
  res_dir: "TEST"

config-genomes:
  CheckM_data: ""
  GTDB: ""
  GTDB_fa_min_af: 0.65
  GTDB_isani: false
  GTDB_mash:
      k: 16,
      s: 5000,
      d: 0.1,
      v: 1.0,
  batch_size: 1500
  low_memory: false
  merge_with: null
  taxonomy_wf:
    enable: false
    rank: null
    taxon: null

config-ccya:
  glyx3_msa: null
  gly1_msa: null
  gly2_msa: null
  gly3_msa: null
  nterdb: null
  glyx3-evalue: null
  glyx3-coverage: null
  glyzip-evalue: null
  glyzip-coverage: null
  iterative-search: True
  iterative-update: True
  max-iteration: 3
  Z: 10000 
  domZ: 10000